// File generated by Stilova Build Assistant.
// Device-agnostic environment-synchronized Firebase Options configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTeo7G4g1wFjaDp5DTnxO61Ptr2TJly4M',
    appId: '1:950696898237:web:0db241dbe8c0028cf951d4',
    messagingSenderId: '950696898237',
    projectId: 'aerial-xylocarp-btgzl',
    authDomain: 'aerial-xylocarp-btgzl.firebaseapp.com',
    storageBucket: 'aerial-xylocarp-btgzl.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTeo7G4g1wFjaDp5DTnxO61Ptr2TJly4M',
    appId: '1:950696898237:android:c1d2ccfa430de208f2',
    messagingSenderId: '950696898237',
    projectId: 'aerial-xylocarp-btgzl',
    storageBucket: 'aerial-xylocarp-btgzl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTeo7G4g1wFjaDp5DTnxO61Ptr2TJly4M',
    appId: '1:950696898237:ios:7f23cdae2cfbfe239e2',
    messagingSenderId: '950696898237',
    projectId: 'aerial-xylocarp-btgzl',
    storageBucket: 'aerial-xylocarp-btgzl.firebasestorage.app',
    iosBundleId: 'com.stilova.app',
  );
}
